### ISSUE TITLE
List widget missing

### ISSUE THREAD

**Issue by dawoe** [kfrancis/geckonet#2]
Hi,

Maybe i'm overlooking something. But is it possible that the list widget is missing in the models ?

https://developer.geckoboard.com/#list

Dave

**Comment by kfrancis** [comment]
Yep - you are correct. I just never added it, didn't personally use it at the time. If you want to add it, feel free - I'll pull it in.

**Comment by kfrancis** [comment]
Done, released in 1.0.6262.18484
