### ISSUE TITLE
Update DatasetFieldType enum

### ISSUE THREAD

**Issue by bjarnef** [kfrancis/geckonet#7]
It would be great to update the DatasetFieldType enum to update pascal case naming convention and more consistent with .NET core enums.
https://github.com/kfrancis/geckonet/blob/9a1d984f9839d87405c003546e59e0865c22641f/Source/Geckonet.Core/Models/DatasetModels.cs#L65-L72

You already have another enum here: https://github.com/kfrancis/geckonet/blob/9a1d984f9839d87405c003546e59e0865c22641f/Source/Geckonet.Sample/Areas/HelpPage/SampleGeneration/SampleDirection.cs

E.g. you could change it to something like this:
```
[DataContract]
public enum DatasetFieldType
{
    [EnumMember(Value = "date")]
    Date,

    [EnumMember(Value = "datetime")]
    DateTime,

    [EnumMember(Value = "number")]
    Number,

    [EnumMember(Value = "percentage")]
    Percentage,

    [EnumMember(Value = "string")]
    String,

    [EnumMember(Value = "money")]
    Money
}
```

```
var obj = new GeckoDataset()
{
    Fields = new Dictionary<string, IDatasetField>()
    {
        {"amount", new DatasetField(DatasetFieldType.Number, "Amount")},
        {"timestamp", new DatasetField(DatasetFieldType.Date, "Date")}
    },
    UniqueBy = new List<string>() { "timestamp" }
};
```

**Comment by kfrancis** [comment]
Fixed in release v1.1.2 - sorry for the wait!
